export const APPLICATION_LABELS = {
  title: "JobTrack",
  dashboardTitle: "Your Job Search",
  dashboardSubtitle: "Track your applications and stay organized throughout your job search.",
  addButton: "Add Application",
  applications: "Your Applications",
  pipeline: "Application Pipeline",
  search: "Search company or job title",
  status: "Status",
  allStatuses: "All Statuses",
  company: "Company",
  jobTitle: "Job Title",
  location: "Location",
  appliedDate: "Applied Date",
  salary: "Salary",
  action: "Action",
  notes: "Notes",
  jobUrl: "Job URL",
  save: "Save Application",
  update: "Update Application",
  cancel: "Cancel",
  edit: "Edit",
  delete: "Delete",
};

export const STATUS_LABELS = {
  APPLIED: "Applied",
  INTERVIEW: "Interview",
  TECHNICAL: "Technical Round",
  HR: "HR Round",
  OFFER: "Offer",
  REJECTED: "Rejected",
  WITHDRAWN: "Withdrawn",
};